import type { ThemeConfig } from 'antd'
import { theme as antdTheme } from 'antd'

const palette = {
  light: {
    background: 'rgba(255, 255, 255, 0.92)',
    surface: 'rgba(255, 255, 255, 0.96)',
    fill: 'rgba(24, 24, 27, 0.045)',
    fillHover: 'rgba(24, 24, 27, 0.075)',
    border: 'rgba(24, 24, 27, 0.1)',
    borderSubtle: 'rgba(24, 24, 27, 0.06)',
    text: '#18181b',
    textSecondary: '#71717a',
    textTertiary: '#a1a1aa',
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    primaryText: '#ffffff',
    shadow: '0 8px 40px rgba(0, 0, 0, 0.12)',
    activeShadow: '0 0 0 3px rgba(37, 99, 235, 0.14)',
  },
  dark: {
    background: 'rgba(24, 24, 27, 0.92)',
    surface: 'rgba(24, 24, 27, 0.96)',
    fill: 'rgba(255, 255, 255, 0.045)',
    fillHover: 'rgba(255, 255, 255, 0.08)',
    border: 'rgba(255, 255, 255, 0.1)',
    borderSubtle: 'rgba(255, 255, 255, 0.06)',
    text: '#fafafa',
    textSecondary: '#a1a1aa',
    textTertiary: '#71717a',
    primary: '#3b82f6',
    primaryHover: '#1d4ed8',
    primaryText: '#ffffff',
    shadow: '0 8px 40px rgba(0, 0, 0, 0.4)',
    activeShadow: '0 0 0 3px rgba(59, 130, 246, 0.2)',
  },
}

export function getAntThemeConfig(dark: boolean): ThemeConfig {
  const color = dark ? palette.dark : palette.light

  return {
    algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
    cssVar: { key: dark ? 'infinite-canvas-dark' : 'infinite-canvas-light' },
    token: {
      colorPrimary: color.primary,
      colorInfo: color.primary,
      colorLink: color.primary,
      colorLinkHover: color.primaryHover,
      colorLinkActive: color.primary,
      colorSuccess: '#22c55e',
      colorWarning: '#eab308',
      colorError: '#ef4444',
      colorTextLightSolid: color.primaryText,
      colorBgBase: dark ? '#09090b' : '#ffffff',
      colorBgContainer: color.background,
      colorBgElevated: color.surface,
      colorFill: color.fill,
      colorFillSecondary: color.fill,
      colorFillTertiary: color.fillHover,
      colorFillQuaternary: color.fillHover,
      colorBorder: color.border,
      colorBorderSecondary: color.borderSubtle,
      colorSplit: color.borderSubtle,
      colorText: color.text,
      colorTextSecondary: color.textSecondary,
      colorTextTertiary: color.textTertiary,
      colorTextPlaceholder: color.textTertiary,
      colorBgLayout: dark ? '#09090b' : '#fafafa',
      colorBgMask: dark ? 'rgba(0, 0, 0, 0.48)' : 'rgba(24, 24, 27, 0.2)',
      borderRadius: 12,
      borderRadiusSM: 8,
      borderRadiusLG: 20,
      boxShadow: color.shadow,
      boxShadowSecondary: color.shadow,
      controlOutline: color.activeShadow,
    },
    components: {
      Button: {
        defaultBg: 'transparent',
        defaultBorderColor: color.border,
        defaultColor: color.textSecondary,
        defaultHoverBg: color.fill,
        defaultHoverBorderColor: color.border,
        defaultHoverColor: color.text,
        primaryShadow: 'none',
      },
      Input: {
        activeBg: color.surface,
        hoverBg: color.surface,
        addonBg: color.fill,
        hoverBorderColor: color.border,
        activeBorderColor: color.primary,
        activeShadow: color.activeShadow,
      },
      Select: {
        selectorBg: color.surface,
        clearBg: color.surface,
        hoverBorderColor: color.border,
        activeBorderColor: color.primary,
        activeOutlineColor: color.activeShadow,
        optionActiveBg: color.fill,
        optionSelectedBg: dark ? 'rgba(59, 130, 246, 0.16)' : 'rgba(37, 99, 235, 0.1)',
        optionSelectedColor: color.text,
      },
      Modal: {
        headerBg: color.background,
        contentBg: color.background,
        footerBg: color.background,
        titleColor: color.text,
      },
      Menu: {
        itemBorderRadius: 10,
        itemActiveBg: color.fill,
        itemHoverBg: color.fill,
        itemSelectedBg: dark ? 'rgba(59, 130, 246, 0.16)' : 'rgba(37, 99, 235, 0.1)',
        itemSelectedColor: color.text,
        itemColor: color.textSecondary,
        itemHoverColor: color.text,
        darkItemHoverBg: palette.dark.fill,
        darkItemSelectedBg: 'rgba(59, 130, 246, 0.16)',
        darkItemSelectedColor: palette.dark.text,
      },
      Table: {
        headerBg: color.fill,
        headerColor: color.textSecondary,
        rowHoverBg: color.fill,
        rowSelectedBg: dark ? 'rgba(59, 130, 246, 0.16)' : 'rgba(37, 99, 235, 0.1)',
        rowSelectedHoverBg: dark ? 'rgba(59, 130, 246, 0.22)' : 'rgba(37, 99, 235, 0.14)',
        borderColor: color.borderSubtle,
      },
    },
  }
}
